### ISSUE TITLE
[BUG] - BOM als dependency geeft problemen

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponenten-vl-ui#49]
**Omschrijf het probleem**
Wanneer de BOM als dependency gebruikt wordt, stoot je op (verschillende) problemen.
1. copy files en replace moeten als dev dependency geïnstalleerd worden bij de afnemer
2. vl-ui-util lijkt niet correct geïnstalleerd te zijn bij het aanroepen van het install:copy:github script
```
> npm explore vl-ui-util -- npm run install:copy:github
npm ERR! It doesn't look like vl-ui-util is installed.
```

**Hoe te reproduceren**
``` JSON
{
  "name": "test",
  "version": "0.0.0",
  "dependencies": {
    "vl-ui-util": "^5.2.5",
    "webcomponenten-vl-ui": "^1.0.0"
  },
  "devDependencies": {
    "vl-ui-util": "^5.2.5",
    "copyfiles": "2.3.0",
    "replace": "1.2.0"
  }
}
```

**Gewenst gedrag**
Succesvolle build. Ik vermoed dat het eenvoudigste zal zijn om het genereren van de demo/documentatie onder een apart script te zetten dat niet uitgevoerd wordt bij een install als dependency.

**Omgeving (gelieve aan te vullen):**
 - Versie component **1.1.1**

**Comment by snijkerm** [comment]
Voor de duidelijkheid, ook al vul ik de dependencies verder aan zoals hierboven (of vul ik niks aan rond vl-ui-util) ik krijg steeds onderstaand probleem:

`[ERROR] npm ERR! It doesn't look like vl-ui-util is installed.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/marcel/.npm/_logs/2020-06-29T15_25_21_622Z-debug.log
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! webcomponenten-vl-ui@1.1.0 install:copy:github: `npm explore vl-ui-util -- npm run install:copy:github`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the webcomponenten-vl-ui@1.1.0 install:copy:github script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/marcel/.npm/_logs/2020-06-29T15_25_21_634Z-debug.log
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! webcomponenten-vl-ui@1.1.0 install:copy: `npm run install:copy:github`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the webcomponenten-vl-ui@1.1.0 install:copy script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/marcel/.npm/_logs/2020-06-29T15_25_21_646Z-debug.log
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.1 (node_modules/chokidar/node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[WARNING] npm WARN vl-ui-input-field@3.1.4 requires a peer of vl-ui-form-validation@github:milieuinfo/webcomponent-vl-ui-form-validation but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN fetch-mock@9.10.3 requires a peer of node-fetch@* but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN jsdom@16.2.2 requires a peer of canvas@^2.5.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN ws@7.3.0 requires a peer of bufferutil@^4.0.1 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN ws@7.3.0 requires a peer of utf-8-validate@^5.0.2 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN sinon-chai@2.14.0 requires a peer of sinon@^1.4.0 || ^2.1.0 || ^3.0.0 || ^4.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN bed@1.0.0-SNAPSHOT No repository field.
[WARNING] npm WARN bed@1.0.0-SNAPSHOT license should be a valid SPDX license expression
[WARNING] npm WARN The package vl-ui-util is included as both a dev and production dependency.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/polymer-cli/node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 1
[ERROR] npm ERR! webcomponenten-vl-ui@1.1.0 install: `npm run analyze && npm run install:copy && npm run doc`
[ERROR] npm ERR! Exit status 1
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the webcomponenten-vl-ui@1.1.0 install script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/marcel/.npm/_logs/2020-06-29T15_25_23_865Z-debug.log`
